// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nihr.Jdr.Dta.Infrastructure.DAL;

#nullable disable

namespace Nihr.Jdr.Dta.Infrastructure.DAL.Migrations
{
    [DbContext(typeof(JdrDtaDbContext))]
    [Migration("20260213173500_AddPersonFk")]
    partial class AddPersonFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Ace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Ace");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeclarationAcceptedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DementiaHistoryFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disabilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EthnicGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherDisabilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherMedicalConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SuffersMemoryProblems")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiagnosisName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PositiveAmyloidPlaque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositiveApoe4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubtypeDiagnosisName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Diagnosis");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Mmse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Mmse");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Moca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Moca");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JdrVolunteerId")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Symptom");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Ace", b =>
                {
                    b.HasOne("Nihr.Jdr.Dta.Domain.Entities.Person", "Person")
                        .WithOne("Ace")
                        .HasForeignKey("Nihr.Jdr.Dta.Domain.Entities.Ace", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Nihr.Jdr.Dta.Domain.Entities.Person", "Person")
                        .WithOne("Appointment")
                        .HasForeignKey("Nihr.Jdr.Dta.Domain.Entities.Appointment", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Diagnosis", b =>
                {
                    b.HasOne("Nihr.Jdr.Dta.Domain.Entities.Person", "Person")
                        .WithOne("Diagnosis")
                        .HasForeignKey("Nihr.Jdr.Dta.Domain.Entities.Diagnosis", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Mmse", b =>
                {
                    b.HasOne("Nihr.Jdr.Dta.Domain.Entities.Person", "Person")
                        .WithOne("Mmse")
                        .HasForeignKey("Nihr.Jdr.Dta.Domain.Entities.Mmse", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Moca", b =>
                {
                    b.HasOne("Nihr.Jdr.Dta.Domain.Entities.Person", "Person")
                        .WithOne("Moca")
                        .HasForeignKey("Nihr.Jdr.Dta.Domain.Entities.Moca", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Symptom", b =>
                {
                    b.HasOne("Nihr.Jdr.Dta.Domain.Entities.Person", "Person")
                        .WithOne("Symptom")
                        .HasForeignKey("Nihr.Jdr.Dta.Domain.Entities.Symptom", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nihr.Jdr.Dta.Domain.Entities.Person", b =>
                {
                    b.Navigation("Ace")
                        .IsRequired();

                    b.Navigation("Appointment")
                        .IsRequired();

                    b.Navigation("Diagnosis")
                        .IsRequired();

                    b.Navigation("Mmse")
                        .IsRequired();

                    b.Navigation("Moca")
                        .IsRequired();

                    b.Navigation("Symptom")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
