<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CsvHelper" Version="33.1.0" />
      <PackageReference Include="Google.Cloud.SecretManager.V1" Version="2.7.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
      <PackageReference Include="MySql.Data" Version="9.6.0" />
      <PackageReference Include="NIHR.Infrastructure.EntityFrameworkCore" Version="1.2.1-preview.2" />
    </ItemGroup>

    <ItemGroup>
      <Content Include=".aws\bunny-ecs-task-definition.json" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DAL\Deployment\" />
      <Folder Include="DAL\Migrations\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nihr.Jdr.Dta.Domain\Nihr.Jdr.Dta.Domain.csproj" />
    </ItemGroup>

</Project>
