name: Deploy Job

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-uat:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: UAT
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.CRNCC_STAGING_IAM_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CRNCC_STAGING_IAM_ACCESS_KEY_SECRET }}
      RDS_SECURITY_GROUP_ID: ${{ secrets.RDS_SECURITY_GROUP_ID }}
      RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
      AWS_DB_SECRET_NAME: ${{ secrets.AWS_DB_SECRET_NAME }}
      AWS_SECRET_NAME: ${{ secrets.AWS_SECRET_NAME }}

  deploy-prod:
    needs: deploy-uat
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: PROD
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.CRNCC_STAGING_IAM_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CRNCC_STAGING_IAM_ACCESS_KEY_SECRET }}
      RDS_SECURITY_GROUP_ID: ${{ secrets.RDS_SECURITY_GROUP_ID }}
      RDS_ENDPOINT: ${{ secrets.RDS_ENDPOINT }}
      AWS_DB_SECRET_NAME: ${{ secrets.AWS_DB_SECRET_NAME }}
      AWS_SECRET_NAME: ${{ secrets.AWS_SECRET_NAME }}
